version: "3.9"

services: 
  dev-db:
    image:  postgres:16.1-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
     - "5432:5432"
    
  test_db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      -"5433:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
     - "8080:8080"
    